### ISSUE TITLE
Trinkets not working right

### ISSUE THREAD

**Issue by cosmicdrak** [Sluimerstand/EquipRecommendedGear#16]
Not sure all the conditions that made it happen but when testing on my Paladin it would not do anything with trinket in the first trinket slot. Even if there was a item level upgrade it would ignore that slot on all 3 specs

**Comment by cosmicdrak** [comment]
Looking through the code, you may want to check if rings are doing the same thing.

**Comment by Sluimerstand** [comment]
Did the item that was an upgrade have a primary stat on it?

**Comment by cosmicdrak** [comment]
I had multiple trinkets with higher item level and one had main Stat others did not

**Comment by cosmicdrak** [comment]
At first I thought it might be due to trinkets not being for my spec but the one with main stat literally only had main Stat and would change main stat based on spec.

**Comment by Sluimerstand** [comment]
I'll have to keep my eye out to test this further, so far I've not been able to reproduce this bug on my end.

**Comment by Sluimerstand** [comment]
Alright, this should be fixed now in the next release.
