### ISSUE TITLE
Chat output message conditions

### ISSUE THREAD

**Issue by Saaappi** [Sluimerstand/EquipRecommendedGear#2]
![image](https://github.com/Sluimerstand/EquipRecommendedGear/assets/36806900/7f7686ac-26c4-4669-8833-6efccdb839cf)

This message is handy (helpful to know it's working when being called from my code); however, can there be an option to have it only show when the addon actually equips gear?

**Comment by Saaappi** [comment]
Given it's an edge case, it's up to you. You designed it to always show an output message, so altering the default behavior will push you in the direction of an options menu.

I can understand if you don't want to spend the time working on that; however, it could serve you well in the long run!

**Comment by Sluimerstand** [comment]
Yeah I was indeed hoping to avoid having to add any settings, so for now I'll leave this one open. If more needs arise for settings, then this one will also be included!

**Comment by Saaappi** [comment]
I'm going to close the issue as unplanned. If I see you add settings in the future, I'll remake the issue.

**Comment by Sluimerstand** [comment]
@Saaappi I don't need to add an options interface to make this work. :')

You can now (v004) use `EquipRecommendedGear.DoTheThing()` to always get chat messages, `EquipRecommendedGear.DoTheThing(1)` to only get a chat message when new gear is equipped, or `EquipRecommendedGear.DoTheThing(0)` to never get chat messages.
