### ISSUE TITLE
DoTheThing() Prints Output Incorrectly

### ISSUE THREAD

**Issue by Saaappi** [Sluimerstand/EquipRecommendedGear#6]
**Description**
When calling the DoTheThing() function with an argument value of 1, the function incorrectly prints output to the chat frame. According to the function's intended behavior, it should only print output to the chat frame when no argument is supplied.

**Steps to Reproduce**
1. Call the DoTheThing() function with an argument value of 1.
1. Observe the output printed to the chat frame.

**Comment by Saaappi** [comment]
It's changing _msg_ to 2, despite me passing 1 to the function. I tested it outside my code by typing it in and received the same behavior.

In other words, I'm passing 1 but DoTheThing is ignoring that and setting it to 2. Are you resetting _msg_ at some point higher up in the function? 🧐

**Comment by Sluimerstand** [comment]
```
-- Set the message variable if it's not set (properly)
if not msg then
	msg = 2
end
if type(msg) ~= "number" then
	msg = 2
end
```

This is the input sanitisation I'm using. You're not passing the number to the function as a string, right?

**Comment by Saaappi** [comment]
Nope. Type is number.

**Comment by Sluimerstand** [comment]
Very weird. I'll have to test this some more when I get home then, but when I tested it upon implementation it was behaving fully as expected.

**Comment by Saaappi** [comment]
local function ERG()
    if UnitAffectingCombat("player") then
        C_Timer.After(1, ERG)
    else
        if IsAddOnLoaded("EquipRecommendedGear") then
            EquipRecommendedGear:DoTheThing(1)
        end
    end
end

I'm on mobile, so I can't format the code here. This is all I'm doing when calling your code.

**Comment by Sluimerstand** [comment]
Using `:` instead of `.` shouldn't matter, right? Again, I'll look into it when I get home tonight. :)

**Comment by Saaappi** [comment]
: is used when a function passes self as the first parameter. A and B are the same.

**A**
sky.foo(a, b)

**B**
sky:foo(self, a, b)

It's syntactic sugar, that's all.

**Comment by Sluimerstand** [comment]
By your logic, wouldn't it pass `self` instead of `1` to the function in your code, then?

**Comment by Sluimerstand** [comment]
Show me how you do that in your code, sometime! I'm still learning new stuff all the time. :D

**Comment by Saaappi** [comment]
Closed! Changing : to . fixed it.
