### ISSUE TITLE
Premature Replacement of Heirloom Items Despite Player Not Outleveling Them

### ISSUE THREAD

**Issue by Saaappi** [Sluimerstand/EquipRecommendedGear#7]
**Description**
Heirloom items are being replaced by gear that is technically higher item level. This occurs despite the player not having outleveled the heirloom items.

![img01](https://github.com/Sluimerstand/EquipRecommendedGear/assets/36806900/3819095c-24aa-48e1-85a4-6e13f9b95402) ![img02](https://github.com/Sluimerstand/EquipRecommendedGear/assets/36806900/31fa2cf3-2c61-440a-b5e1-a790e9533ab6)

**Steps to Reproduce**
1. Obtain an heirloom item for a character.
1. Ensure the character's level has not surpassed the level range of the heirloom item.
1. Progress through the game and acquire an item that is higher level than the heirloom.
1. Observe that the heirloom item is unexpectedly replaced by the gear.

**Comment by Sluimerstand** [comment]
Ah, weapons. The bane of my existence. I probably didn't add the heirloom check for these as they run on a separate bit of code than the other slots, I'll look into it!

**Comment by Saaappi** [comment]
Weapons seem to no longer be replaced as intended.
